# Generated by Django 2.2.24 on 2025-02-01 13:22

from django.db import migrations, models
from django.db.models import Case, When, Value


def fill_new_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')

    Flat.objects.update(
        new_building=Case(
            When(construction_year__gte=2015, then=Value(True)),
            default=Value(False),
            output_field=models.BooleanField()
        )
    )


def reverse_fill_new_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Flat.objects.update(new_building=None)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(fill_new_building, reverse_fill_new_building),
    ]
