# Generated by Django 2.2.24 on 2025-02-01 13:56

from django.db import migrations
from phonenumbers import is_valid_number, parse, is_possible_number


def normalize_phone_numbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flats = Flat.objects.all()

    updates = []

    for flat in flats:
        if not flat.owners_phonenumber:
            flat.owner_pure_phone = None
            updates.append(flat)
            continue

        raw_phone_number = flat.owners_phonenumber
        parsed_phone_number = parse(raw_phone_number, 'RU')

        if not is_possible_number(parsed_phone_number) or not is_valid_number(parsed_phone_number):
            flat.owner_pure_phone = None
        else:
            flat.owner_pure_phone = parsed_phone_number

        updates.append(flat)

    Flat.objects.bulk_update(updates, ['owner_pure_phone'])


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(normalize_phone_numbers),
    ]
