# Generated by Django 2.2.24 on 2025-01-28 18:50

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20250121_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='owner_pure_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='RU', verbose_name='Нормализованный номер владельца'),
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder', models.CharField(max_length=200, verbose_name='ФИО владельца')),
                ('holder_phone', models.CharField(max_length=20, verbose_name='Номер владельца')),
                ('holder_pure_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='RU', verbose_name='Нормализованный номер владельца')),
                ('holder_flat', models.ManyToManyField(related_name='holder_flats', to='property.Flat', verbose_name='Квартиры в собственности')),
            ],
        ),
    ]
