# Generated by Django 2.2.24 on 2025-02-01 17:41

from django.db import migrations


def migrate_flats_to_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.iterator():
        if flat.owner:
            owner, created = Owner.objects.get_or_create(
                name=flat.owner,
                defaults={
                    'phone': flat.owners_phonenumber,
                    'pure_phone': flat.owner_pure_phone,
                }
            )
            flat.owners.add(owner)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_add_owner'),
    ]
    operations = [
        migrations.RunPython(migrate_flats_to_owners),
    ]
