# Generated by Django 2.2.24 on 2025-01-28 18:51

from django.db import migrations


def migrate_flats_to_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.all():
        owner, created = Owner.objects.get_or_create(
            holder=flat.owner,
            defaults={
                'holder_phone': flat.owners_phone,
                'holder_pure_phone': flat.owner_pure_phone,
            }
        )
        owner.holder_flat.add(flat)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20250128_2150'),
    ]

    operations = [
        migrations.RunPython(migrate_flats_to_owners),
    ]
