# Generated by Django 2.2.24 on 2025-01-28 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20250128_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='owners',
        ),
    ]
